{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "metadata": {
        "id": "dUJpj-k8cO8h"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "mHuEcbQuVfJ9"
      },
      "outputs": [],
      "source": [
        "import subprocess, sys\n",
        "\n",
        "packages = [\n",
        "    \"transformers\",\n",
        "    \"datasets\",\n",
        "    \"torch\",\n",
        "    \"torchvision\",\n",
        "    \"albumentations\",\n",
        "    \"segmentation_models_pytorch\",\n",
        "    \"matplotlib\",\n",
        "    \"numpy\",\n",
        "    \"Pillow>=9.0,<11.0\",   # ← pinned: torchvision incompatible with Pillow 11+\n",
        "    \"tqdm\",\n",
        "    \"scikit-learn\",\n",
        "]\n",
        "\n",
        "print(\"📦 Installing packages (this may take ~60 s)...\")\n",
        "subprocess.check_call(\n",
        "    [sys.executable, \"-m\", \"pip\", \"install\", \"--quiet\", \"--upgrade\"] + packages\n",
        ")\n",
        "print(\"✅ Packages installed — restarting runtime to load clean versions...\\n\")\n",
        "\n",
        "# Force Colab to reload all packages with the correct Pillow version.\n",
        "# Everything below this point runs AFTER the restart.\n",
        "import os\n",
        "os.kill(os.getpid(), 9)\n",
        "\n",
        "\n",
        "# ════════════════════════════════════════════════════════════\n",
        "# ▶ AFTER the runtime restarts, run THIS cell again from here.\n",
        "#   The install block above will finish instantly (already cached)\n",
        "#   and execution will continue through imports → device → seed.\n",
        "# ════════════════════════════════════════════════════════════\n",
        "\n",
        "\n",
        "# ── 2. IMPORTS ──────────────────────────────────────────────\n",
        "import os\n",
        "import random\n",
        "import warnings\n",
        "warnings.filterwarnings(\"ignore\")\n",
        "\n",
        "# Numeric & visualisation\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.patches as mpatches\n",
        "from PIL import Image\n",
        "from tqdm import tqdm\n",
        "\n",
        "# PyTorch core\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "import torchvision\n",
        "import torchvision.transforms as T\n",
        "import torchvision.transforms.functional as TF\n",
        "\n",
        "# Augmentations\n",
        "import albumentations as A\n",
        "from albumentations.pytorch import ToTensorV2\n",
        "\n",
        "# Segmentation model library\n",
        "import segmentation_models_pytorch as smp\n",
        "from segmentation_models_pytorch import Unet, FPN, DeepLabV3Plus\n",
        "\n",
        "# HuggingFace ecosystem\n",
        "from transformers import (\n",
        "    SegformerForSemanticSegmentation,\n",
        "    SegformerFeatureExtractor,\n",
        "    SegformerConfig,\n",
        ")\n",
        "from datasets import load_dataset\n",
        "\n",
        "# Scikit-learn utilities\n",
        "from sklearn.metrics import (\n",
        "    jaccard_score,\n",
        "    f1_score,\n",
        "    confusion_matrix,\n",
        "    classification_report,\n",
        ")\n",
        "\n",
        "print(\"✅ All libraries imported.\\n\")\n",
        "\n",
        "\n",
        "# ── 3. DEVICE CONFIGURATION ─────────────────────────────────\n",
        "if torch.cuda.is_available():\n",
        "    DEVICE = torch.device(\"cuda\")\n",
        "    torch.backends.cudnn.benchmark = True\n",
        "    torch.backends.cudnn.deterministic = True\n",
        "elif torch.backends.mps.is_available():\n",
        "    DEVICE = torch.device(\"mps\")\n",
        "else:\n",
        "    DEVICE = torch.device(\"cpu\")\n",
        "\n",
        "print(f\"🖥️  Device set to: {DEVICE}\\n\")\n",
        "\n",
        "\n",
        "# ── 4. REPRODUCIBILITY ──────────────────────────────────────\n",
        "SEED = 42\n",
        "\n",
        "def set_seed(seed: int = SEED) -> None:\n",
        "    \"\"\"Fix all random seeds for full reproducibility.\"\"\"\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed(seed)\n",
        "    torch.cuda.manual_seed_all(seed)\n",
        "    os.environ[\"PYTHONHASHSEED\"] = str(seed)\n",
        "\n",
        "set_seed(SEED)\n",
        "print(f\"🎲 Random seed fixed to: {SEED}\\n\")\n",
        "\n",
        "\n",
        "# ── 5. DIRECTORY STRUCTURE ──────────────────────────────────\n",
        "DIRS = [\n",
        "    \"/content/data/train/images\",\n",
        "    \"/content/data/train/masks\",\n",
        "    \"/content/data/val/images\",\n",
        "    \"/content/data/val/masks\",\n",
        "    \"/content/data/test/images\",\n",
        "    \"/content/outputs\",\n",
        "]\n",
        "\n",
        "for path in DIRS:\n",
        "    os.makedirs(path, exist_ok=True)\n",
        "\n",
        "print(\"📁 Folder structure created:\")\n",
        "for path in DIRS:\n",
        "    print(f\"   {path}\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ── 6. SETUP SUMMARY ────────────────────────────────────────\n",
        "print(\"=\" * 55)\n",
        "print(\"  🚀 ENVIRONMENT SETUP COMPLETE\")\n",
        "print(\"=\" * 55)\n",
        "print(f\"  Python  : {sys.version.split()[0]}\")\n",
        "print(f\"  PyTorch : {torch.__version__}\")\n",
        "print(f\"  Pillow  : {__import__('PIL').__version__}\")\n",
        "print(f\"  Device  : {DEVICE}\")\n",
        "\n",
        "if DEVICE.type == \"cuda\":\n",
        "    gpu_name  = torch.cuda.get_device_name(0)\n",
        "    gpu_mem   = torch.cuda.get_device_properties(0).total_memory / 1024**3\n",
        "    allocated = torch.cuda.memory_allocated(0) / 1024**3\n",
        "    print(f\"  GPU     : {gpu_name}\")\n",
        "    print(f\"  VRAM    : {gpu_mem:.2f} GB total  |  {allocated:.2f} GB in use\")\n",
        "    print(f\"  CUDA    : {torch.version.cuda}\")\n",
        "elif DEVICE.type == \"mps\":\n",
        "    print(\"  GPU     : Apple Silicon (MPS)\")\n",
        "else:\n",
        "    print(\"  GPU     : Not available — running on CPU\")\n",
        "\n",
        "print(f\"  Seed    : {SEED}\")\n",
        "print(\"=\" * 55)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import numpy as np\n",
        "from PIL import Image\n",
        "from tqdm import tqdm\n",
        "\n",
        "import torch\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "\n",
        "import albumentations as A\n",
        "from albumentations.pytorch import ToTensorV2\n",
        "import os\n",
        "os.makedirs(\"/content/outputs\", exist_ok=True)\n",
        "\n",
        "# ── CLASS ID → SEQUENTIAL LABEL MAPPING ─────────────────────\n",
        "# Raw mask pixel values → contiguous 0-based indices for CrossEntropyLoss\n",
        "CLASS_ID_TO_LABEL = {\n",
        "    100:   0,   # Trees\n",
        "    200:   1,   # Lush Bushes\n",
        "    300:   2,   # Dry Grass\n",
        "    500:   3,   # Dry Bushes\n",
        "    550:   4,   # Ground Clutter\n",
        "    600:   5,   # Flowers\n",
        "    700:   6,   # Logs\n",
        "    800:   7,   # Rocks\n",
        "    7100:  8,   # Landscape\n",
        "    10000: 9,   # Sky\n",
        "}\n",
        "\n",
        "# Human-readable class names (useful for visualisation / metrics)\n",
        "CLASS_NAMES = [\n",
        "    \"Trees\",         # 0\n",
        "    \"Lush Bushes\",   # 1\n",
        "    \"Dry Grass\",     # 2\n",
        "    \"Dry Bushes\",    # 3\n",
        "    \"Ground Clutter\",# 4\n",
        "    \"Flowers\",       # 5\n",
        "    \"Logs\",          # 6\n",
        "    \"Rocks\",         # 7\n",
        "    \"Landscape\",     # 8\n",
        "    \"Sky\",           # 9\n",
        "]\n",
        "\n",
        "NUM_CLASSES = len(CLASS_NAMES)   # 10\n",
        "\n",
        "# ImageNet mean & std — used for normalising RGB images\n",
        "IMAGENET_MEAN = (0.485, 0.456, 0.406)\n",
        "IMAGENET_STD  = (0.229, 0.224, 0.225)\n",
        "\n",
        "IMAGE_SIZE = 512   # both H and W are resized to this value\n",
        "\n",
        "\n",
        "# ── DATASET CLASS ────────────────────────────────────────────\n",
        "class DesertSegmentationDataset(Dataset):\n",
        "    \"\"\"\n",
        "    PyTorch Dataset for the Desert Environment Segmentation task.\n",
        "\n",
        "    Directory layout expected:\n",
        "        root_dir/\n",
        "            train/\n",
        "                images/   *.jpg / *.png\n",
        "                masks/    *.png  (grayscale, raw class IDs)\n",
        "            val/\n",
        "                images/\n",
        "                masks/\n",
        "            test/\n",
        "                images/   (masks optional for test split)\n",
        "                masks/\n",
        "\n",
        "    Args:\n",
        "        root_dir  (str)            : Path to the dataset root.\n",
        "        split     (str)            : One of \"train\", \"val\", \"test\".\n",
        "        transform (A.Compose|None) : Albumentations pipeline.\n",
        "                                     If None a safe default is applied.\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self, root_dir: str, split: str, transform=None):\n",
        "        assert split in (\"train\", \"val\", \"test\"), \\\n",
        "            f\"split must be 'train', 'val', or 'test', got '{split}'\"\n",
        "\n",
        "        self.split      = split\n",
        "        self.transform  = transform\n",
        "        self.id_to_label = CLASS_ID_TO_LABEL\n",
        "\n",
        "        self.image_dir = os.path.join(root_dir, split, \"Color_Images\")\n",
        "        self.mask_dir  = os.path.join(root_dir, split, \"Segmentation\")\n",
        "\n",
        "        if not os.path.isdir(self.image_dir):\n",
        "            raise FileNotFoundError(f\"Image directory not found: {self.image_dir}\")\n",
        "\n",
        "        # ── collect filenames ────────────────────────────────\n",
        "        valid_exts = {\".jpg\", \".jpeg\", \".png\", \".bmp\", \".tif\", \".tiff\"}\n",
        "        self.image_names = sorted(\n",
        "            f for f in os.listdir(self.image_dir)\n",
        "            if os.path.splitext(f)[1].lower() in valid_exts\n",
        "        )\n",
        "\n",
        "        if len(self.image_names) == 0:\n",
        "            raise RuntimeError(f\"No images found in {self.image_dir}\")\n",
        "\n",
        "        # Build a lookup table (LUT) once for fast numpy remapping:\n",
        "        #   lut[raw_id] = sequential_label\n",
        "        # Raw IDs go up to 10 000, so a 10 001-element array is enough.\n",
        "        max_id = max(self.id_to_label.keys()) + 1   # 10 001\n",
        "        self._lut = np.zeros(max_id, dtype=np.int64)\n",
        "        for raw_id, label in self.id_to_label.items():\n",
        "            self._lut[raw_id] = label\n",
        "\n",
        "    # ── helpers ──────────────────────────────────────────────\n",
        "\n",
        "    def _remap_mask(self, mask_np: np.ndarray) -> np.ndarray:\n",
        "        \"\"\"\n",
        "        Convert a 2-D array of raw class IDs to sequential labels\n",
        "        using the pre-built LUT (vectorised, no Python loops).\n",
        "        Pixels with unknown IDs silently map to 0.\n",
        "        \"\"\"\n",
        "        # Clip to LUT bounds so unknown IDs don't cause index errors\n",
        "        safe = np.clip(mask_np.astype(np.int64), 0, len(self._lut) - 1)\n",
        "        return self._lut[safe]\n",
        "\n",
        "    def _stem(self, image_name: str) -> str:\n",
        "        \"\"\"Return the filename without extension.\"\"\"\n",
        "        return os.path.splitext(image_name)[0]\n",
        "\n",
        "    def _find_mask_path(self, image_name: str) -> str | None:\n",
        "        \"\"\"\n",
        "        Try to locate the matching mask file.\n",
        "        Falls back gracefully for test splits that may lack masks.\n",
        "        \"\"\"\n",
        "        stem = self._stem(image_name)\n",
        "        for ext in (\".png\", \".jpg\", \".jpeg\", \".bmp\", \".tif\", \".tiff\"):\n",
        "            candidate = os.path.join(self.mask_dir, stem + ext)\n",
        "            if os.path.isfile(candidate):\n",
        "                return candidate\n",
        "        return None   # mask not found (acceptable for test split)\n",
        "\n",
        "    # ── Dataset interface ────────────────────────────────────\n",
        "\n",
        "    def __len__(self) -> int:\n",
        "        return len(self.image_names)\n",
        "\n",
        "    def __getitem__(self, idx: int):\n",
        "        image_name = self.image_names[idx]\n",
        "\n",
        "        # ── load image (H×W×3, uint8) ────────────────────────\n",
        "        image_path = os.path.join(self.image_dir, image_name)\n",
        "        image = np.array(\n",
        "            Image.open(image_path).convert(\"RGB\"),\n",
        "            dtype=np.uint8\n",
        "        )\n",
        "\n",
        "        # ── load mask (H×W, uint16/int32 raw IDs) ───────────\n",
        "        mask_path = self._find_mask_path(image_name)\n",
        "\n",
        "        if mask_path is not None:\n",
        "            # Read as-is (grayscale) to preserve large pixel values\n",
        "            raw_mask = np.array(\n",
        "                Image.open(mask_path).convert(\"I\"),   # 32-bit grayscale\n",
        "                dtype=np.int32\n",
        "            )\n",
        "            mask = self._remap_mask(raw_mask).astype(np.int64)\n",
        "        else:\n",
        "            # Test images without a mask: return a blank mask\n",
        "            mask = np.zeros(image.shape[:2], dtype=np.int64)\n",
        "\n",
        "        # ── resize to 512×512 before augmentation ───────────\n",
        "        # Use PIL for high-quality resizing, then convert back to numpy\n",
        "        image = np.array(\n",
        "            Image.fromarray(image).resize(\n",
        "                (IMAGE_SIZE, IMAGE_SIZE), Image.BILINEAR\n",
        "            ),\n",
        "            dtype=np.uint8\n",
        "        )\n",
        "        mask = np.array(\n",
        "            Image.fromarray(mask.astype(np.int32), mode=\"I\").resize(\n",
        "                (IMAGE_SIZE, IMAGE_SIZE), Image.NEAREST   # no interpolation on labels\n",
        "            ),\n",
        "            dtype=np.int64\n",
        "        )\n",
        "\n",
        "        # ── apply albumentations transform ───────────────────\n",
        "        if self.transform is not None:\n",
        "            augmented = self.transform(image=image, mask=mask)\n",
        "            image = augmented[\"image\"]   # float32 tensor after ToTensorV2\n",
        "            mask  = augmented[\"mask\"]    # long tensor\n",
        "        else:\n",
        "            # Minimal safe fallback: just to-tensor + normalise\n",
        "            _fallback = A.Compose([\n",
        "                A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),\n",
        "                ToTensorV2(),\n",
        "            ])\n",
        "            augmented = _fallback(image=image, mask=mask)\n",
        "            image = augmented[\"image\"]\n",
        "            mask  = augmented[\"mask\"]\n",
        "\n",
        "        # Ensure correct dtypes\n",
        "        image = image.float()           # (3, H, W) float32\n",
        "        mask  = mask.long()             # (H, W)    int64\n",
        "\n",
        "        return image, mask\n",
        "\n",
        "    def __repr__(self) -> str:\n",
        "        return (\n",
        "            f\"DesertSegmentationDataset(\"\n",
        "            f\"split='{self.split}', \"\n",
        "            f\"n_samples={len(self)}, \"\n",
        "            f\"n_classes={NUM_CLASSES})\"\n",
        "        )\n",
        "\n",
        "\n",
        "# ── AUGMENTATION PIPELINES ───────────────────────────────────\n",
        "\n",
        "def get_train_transforms() -> A.Compose:\n",
        "    \"\"\"\n",
        "    Strong augmentation for training:\n",
        "      spatial  → random crop, horizontal flip, rotation\n",
        "      colour   → brightness / contrast / saturation / hue jitter\n",
        "      finalise → normalise (ImageNet stats) + convert to tensor\n",
        "    \"\"\"\n",
        "    return A.Compose([\n",
        "        # ── spatial augmentations ────────────────────────────\n",
        "        A.HorizontalFlip(p=0.5),\n",
        "        A.RandomRotate90(p=0.3),\n",
        "        A.Rotate(limit=15, border_mode=0, p=0.4),       # up to ±15°\n",
        "        A.RandomResizedCrop(\n",
        "            size=(IMAGE_SIZE, IMAGE_SIZE),\n",
        "            scale=(0.7, 1.0),    # crop between 70 % and 100 % of the image\n",
        "            ratio=(0.75, 1.33),\n",
        "            p=0.5,\n",
        "        ),\n",
        "\n",
        "        # ── colour / texture augmentations ───────────────────\n",
        "        A.ColorJitter(\n",
        "            brightness=0.3,\n",
        "            contrast=0.3,\n",
        "            saturation=0.3,\n",
        "            hue=0.1,\n",
        "            p=0.6,\n",
        "        ),\n",
        "        A.RandomGamma(gamma_limit=(80, 120), p=0.3),\n",
        "        A.GaussNoise(var_limit=(10.0, 50.0), p=0.2),\n",
        "        A.GaussianBlur(blur_limit=(3, 5), p=0.2),\n",
        "\n",
        "        # ── normalise + to tensor ─────────────────────────────\n",
        "        A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),\n",
        "        ToTensorV2(),\n",
        "    ])\n",
        "\n",
        "\n",
        "def get_val_transforms() -> A.Compose:\n",
        "    \"\"\"\n",
        "    Minimal transform for validation / inference:\n",
        "    only normalise (resize already done inside __getitem__).\n",
        "    \"\"\"\n",
        "    return A.Compose([\n",
        "        A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),\n",
        "        ToTensorV2(),\n",
        "    ])\n",
        "\n",
        "\n",
        "# ── DATALOADER FACTORY ───────────────────────────────────────\n",
        "\n",
        "def get_dataloaders(\n",
        "    root_dir:   str,\n",
        "    batch_size: int = 8,\n",
        "    num_workers: int = 2,\n",
        "    pin_memory: bool = True,\n",
        ") -> tuple[DataLoader, DataLoader]:\n",
        "    \"\"\"\n",
        "    Build and return (train_loader, val_loader).\n",
        "\n",
        "    Args:\n",
        "        root_dir    : Path to the dataset root directory.\n",
        "        batch_size  : Samples per batch (default 8).\n",
        "        num_workers : Parallel data-loading workers (default 2).\n",
        "        pin_memory  : Set True when training on a CUDA GPU.\n",
        "\n",
        "    Returns:\n",
        "        (train_loader, val_loader) as a tuple of DataLoader objects.\n",
        "    \"\"\"\n",
        "\n",
        "    # ── datasets ─────────────────────────────────────────────\n",
        "    train_dataset = DesertSegmentationDataset(\n",
        "        root_dir  = root_dir,\n",
        "        split     = \"train\",\n",
        "        transform = get_train_transforms(),\n",
        "    )\n",
        "\n",
        "    val_dataset = DesertSegmentationDataset(\n",
        "        root_dir  = root_dir,\n",
        "        split     = \"val\",\n",
        "        transform = get_val_transforms(),\n",
        "    )\n",
        "\n",
        "    print(f\"📂 {train_dataset}\")\n",
        "    print(f\"📂 {val_dataset}\")\n",
        "\n",
        "    # ── loaders ──────────────────────────────────────────────\n",
        "    train_loader = DataLoader(\n",
        "        train_dataset,\n",
        "        batch_size  = batch_size,\n",
        "        shuffle     = True,         # shuffle every epoch during training\n",
        "        num_workers = num_workers,\n",
        "        pin_memory  = pin_memory,\n",
        "        drop_last   = True,         # avoids batch-norm issues on tiny last batch\n",
        "    )\n",
        "\n",
        "    val_loader = DataLoader(\n",
        "        val_dataset,\n",
        "        batch_size  = batch_size,\n",
        "        shuffle     = False,        # keep order stable for reproducible metrics\n",
        "        num_workers = num_workers,\n",
        "        pin_memory  = pin_memory,\n",
        "        drop_last   = False,\n",
        "    )\n",
        "\n",
        "    print(f\"\\n✅ Train batches : {len(train_loader)}\")\n",
        "    print(f\"✅ Val   batches : {len(val_loader)}\")\n",
        "\n",
        "    return train_loader, val_loader\n",
        "\n",
        "\n",
        "# ── EXAMPLE USAGE ────────────────────────────────────────────\n",
        "if __name__ == \"__main__\":\n",
        "    import matplotlib.pyplot as plt\n",
        "\n",
        "    ROOT_DIR = \"/content/drive/MyDrive/Offroad_Segmentation_Training_Dataset\"\n",
        "\n",
        "    # ── 1. Create dataloaders ─────────────────────────────────\n",
        "    train_loader, val_loader = get_dataloaders(\n",
        "        root_dir    = ROOT_DIR,\n",
        "        batch_size  = 8,\n",
        "        num_workers = 2,\n",
        "        pin_memory  = torch.cuda.is_available(),\n",
        "    )\n",
        "\n",
        "    # ── 2. Inspect a single batch ─────────────────────────────\n",
        "    images, masks = next(iter(train_loader))\n",
        "\n",
        "    print(f\"\\n── Batch inspection ──────────────────────────\")\n",
        "    print(f\"Image tensor : {images.shape}  dtype={images.dtype}\")\n",
        "    print(f\"Mask  tensor : {masks.shape}   dtype={masks.dtype}\")\n",
        "    print(f\"Pixel value range  → [{images.min():.2f}, {images.max():.2f}]\")\n",
        "    print(f\"Unique mask labels → {masks.unique().tolist()}\")\n",
        "\n",
        "    # ── 3. Visualise one sample ───────────────────────────────\n",
        "    # De-normalise the image for display\n",
        "    MEAN = torch.tensor(IMAGENET_MEAN).view(3, 1, 1)\n",
        "    STD  = torch.tensor(IMAGENET_STD ).view(3, 1, 1)\n",
        "\n",
        "    img_display = (images[0] * STD + MEAN).permute(1, 2, 0).clamp(0, 1).numpy()\n",
        "    mask_display = masks[0].numpy()\n",
        "\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
        "    axes[0].imshow(img_display)\n",
        "    axes[0].set_title(\"Input Image (de-normalised)\")\n",
        "    axes[0].axis(\"off\")\n",
        "\n",
        "    im = axes[1].imshow(mask_display, cmap=\"tab10\", vmin=0, vmax=NUM_CLASSES - 1)\n",
        "    axes[1].set_title(\"Segmentation Mask (sequential labels)\")\n",
        "    axes[1].axis(\"off\")\n",
        "\n",
        "    # Add a colour-coded legend\n",
        "    cmap   = plt.get_cmap(\"tab10\")\n",
        "    legend = [\n",
        "        plt.Rectangle((0, 0), 1, 1, color=cmap(i / NUM_CLASSES))\n",
        "        for i in range(NUM_CLASSES)\n",
        "    ]\n",
        "    fig.legend(legend, CLASS_NAMES, loc=\"lower center\",\n",
        "               ncol=5, fontsize=9, frameon=True)\n",
        "\n",
        "    plt.suptitle(\"Desert Segmentation — Sample Visualisation\", fontsize=13)\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(\"/content/outputs/sample_batch.png\", dpi=150, bbox_inches=\"tight\")\n",
        "    plt.show()\n",
        "    print(\"\\n💾 Saved preview → /content/outputs/sample_batch.png\")"
      ],
      "metadata": {
        "id": "LYdgXinvWZAo"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================\n",
        "# DEEPLABV3+ TRAINING — DESERT SEGMENTATION\n",
        "# ============================================================\n",
        "!pip install -q segmentation_models_pytorch\n",
        "import os\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from torch.optim import AdamW\n",
        "from torch.optim.lr_scheduler import CosineAnnealingLR\n",
        "import segmentation_models_pytorch as smp\n",
        "from tqdm import tqdm\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "\n",
        "# ── CONFIG ───────────────────────────────────────────────────\n",
        "ROOT_DIR = \"/content/drive/MyDrive/Offroad_Segmentation_Training_Dataset\"\n",
        "OUTPUT_DIR  = \"/content/outputs\"\n",
        "NUM_CLASSES = 10\n",
        "BATCH_SIZE  = 8\n",
        "NUM_WORKERS = 2\n",
        "EPOCHS      = 15\n",
        "LR          = 3e-4\n",
        "DEVICE      = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "\n",
        "print(f\"🖥️  Training on: {DEVICE}\")\n",
        "\n",
        "\n",
        "# ── MODEL ────────────────────────────────────────────────────\n",
        "def get_model():\n",
        "    model = smp.DeepLabV3Plus(\n",
        "        encoder_name    = \"resnet50\",       # pretrained backbone\n",
        "        encoder_weights = \"imagenet\",       # start from ImageNet weights\n",
        "        in_channels     = 3,                # RGB input\n",
        "        classes         = NUM_CLASSES,      # 10 desert classes\n",
        "        activation      = None,             # raw logits (loss handles this)\n",
        "    )\n",
        "    return model.to(DEVICE)\n",
        "\n",
        "\n",
        "# ── LOSS FUNCTION ────────────────────────────────────────────\n",
        "# Combines CrossEntropy + Dice for better boundary segmentation\n",
        "class CombinedLoss(nn.Module):\n",
        "    def __init__(self, num_classes=NUM_CLASSES, ignore_index=255):\n",
        "        super().__init__()\n",
        "        self.ce_loss   = nn.CrossEntropyLoss(ignore_index=ignore_index)\n",
        "        self.dice_loss = smp.losses.DiceLoss(\n",
        "            mode         = \"multiclass\",\n",
        "            ignore_index = ignore_index,\n",
        "        )\n",
        "\n",
        "    def forward(self, logits, targets):\n",
        "        ce   = self.ce_loss(logits, targets)\n",
        "        dice = self.dice_loss(logits, targets)\n",
        "        return ce + dice   # equal weight; tweak ratio if needed\n",
        "\n",
        "\n",
        "# ── METRICS ─────────────────────────────────────────────────\n",
        "def compute_iou(preds, targets, num_classes=NUM_CLASSES):\n",
        "    \"\"\"\n",
        "    Compute mean IoU across all classes.\n",
        "    Ignores classes not present in the batch.\n",
        "    \"\"\"\n",
        "    ious = []\n",
        "    preds   = preds.cpu().numpy().flatten()\n",
        "    targets = targets.cpu().numpy().flatten()\n",
        "\n",
        "    for cls in range(num_classes):\n",
        "        pred_mask   = (preds   == cls)\n",
        "        target_mask = (targets == cls)\n",
        "        intersection = (pred_mask & target_mask).sum()\n",
        "        union        = (pred_mask | target_mask).sum()\n",
        "        if union == 0:\n",
        "            continue          # class not present — skip\n",
        "        ious.append(intersection / union)\n",
        "\n",
        "    return np.mean(ious) if ious else 0.0\n",
        "\n",
        "\n",
        "# ── TRAINING LOOP ────────────────────────────────────────────\n",
        "def train_one_epoch(model, loader, optimizer, criterion):\n",
        "    model.train()\n",
        "    total_loss, total_iou = 0.0, 0.0\n",
        "\n",
        "    loop = tqdm(loader, desc=\"  Train\", leave=False)\n",
        "    for images, masks in loop:\n",
        "        images = images.to(DEVICE)\n",
        "        masks  = masks.to(DEVICE)\n",
        "\n",
        "        optimizer.zero_grad()\n",
        "        logits = model(images)                      # (B, C, H, W)\n",
        "        loss   = criterion(logits, masks)\n",
        "        loss.backward()\n",
        "        optimizer.step()\n",
        "\n",
        "        preds = logits.argmax(dim=1)                # (B, H, W)\n",
        "        iou   = compute_iou(preds, masks)\n",
        "\n",
        "        total_loss += loss.item()\n",
        "        total_iou  += iou\n",
        "        loop.set_postfix(loss=f\"{loss.item():.4f}\", iou=f\"{iou:.4f}\")\n",
        "\n",
        "    n = len(loader)\n",
        "    return total_loss / n, total_iou / n\n",
        "\n",
        "\n",
        "# ── VALIDATION LOOP ──────────────────────────────────────────\n",
        "def validate(model, loader, criterion):\n",
        "    model.eval()\n",
        "    total_loss, total_iou = 0.0, 0.0\n",
        "\n",
        "    with torch.no_grad():\n",
        "        loop = tqdm(loader, desc=\"  Val  \", leave=False)\n",
        "        for images, masks in loop:\n",
        "            images = images.to(DEVICE)\n",
        "            masks  = masks.to(DEVICE)\n",
        "\n",
        "            logits = model(images)\n",
        "            loss   = criterion(logits, masks)\n",
        "            preds  = logits.argmax(dim=1)\n",
        "            iou    = compute_iou(preds, masks)\n",
        "\n",
        "            total_loss += loss.item()\n",
        "            total_iou  += iou\n",
        "            loop.set_postfix(loss=f\"{loss.item():.4f}\", iou=f\"{iou:.4f}\")\n",
        "\n",
        "    n = len(loader)\n",
        "    return total_loss / n, total_iou / n\n",
        "\n",
        "\n",
        "# ── PLOT TRAINING CURVES ─────────────────────────────────────\n",
        "def plot_curves(history):\n",
        "    epochs = range(1, len(history[\"train_loss\"]) + 1)\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "    # Loss\n",
        "    axes[0].plot(epochs, history[\"train_loss\"], label=\"Train Loss\")\n",
        "    axes[0].plot(epochs, history[\"val_loss\"],   label=\"Val Loss\")\n",
        "    axes[0].set_title(\"Loss\")\n",
        "    axes[0].set_xlabel(\"Epoch\")\n",
        "    axes[0].legend()\n",
        "    axes[0].grid(True)\n",
        "\n",
        "    # IoU\n",
        "    axes[1].plot(epochs, history[\"train_iou\"], label=\"Train mIoU\")\n",
        "    axes[1].plot(epochs, history[\"val_iou\"],   label=\"Val mIoU\")\n",
        "    axes[1].set_title(\"Mean IoU\")\n",
        "    axes[1].set_xlabel(\"Epoch\")\n",
        "    axes[1].legend()\n",
        "    axes[1].grid(True)\n",
        "\n",
        "    plt.suptitle(\"DeepLabV3+ Training Curves\", fontsize=13)\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(os.path.join(OUTPUT_DIR, \"training_curves.png\"),\n",
        "                dpi=150, bbox_inches=\"tight\")\n",
        "    plt.show()\n",
        "    print(\"💾 Saved → /content/outputs/training_curves.png\")\n",
        "\n",
        "\n",
        "# ── MAIN TRAINING FUNCTION ───────────────────────────────────\n",
        "def train():\n",
        "    # ── dataloaders (from Cell 2) ────────────────────────────\n",
        "    train_loader, val_loader = get_dataloaders(\n",
        "        root_dir    = ROOT_DIR,\n",
        "        batch_size  = BATCH_SIZE,\n",
        "        num_workers = NUM_WORKERS,\n",
        "        pin_memory  = (DEVICE.type == \"cuda\"),\n",
        "    )\n",
        "\n",
        "    # ── model, loss, optimizer, scheduler ────────────────────\n",
        "    model     = get_model()\n",
        "    criterion = CombinedLoss()\n",
        "    optimizer = AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
        "    scheduler = CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)\n",
        "\n",
        "    print(f\"\\n🏋️  Starting training for {EPOCHS} epochs...\\n\")\n",
        "\n",
        "    best_val_iou = 0.0\n",
        "    best_path    = os.path.join(OUTPUT_DIR, \"best_model.pth\")\n",
        "\n",
        "    history = {\n",
        "        \"train_loss\": [], \"train_iou\": [],\n",
        "        \"val_loss\":   [], \"val_iou\":   [],\n",
        "    }\n",
        "\n",
        "    for epoch in range(1, EPOCHS + 1):\n",
        "        print(f\"Epoch [{epoch:02d}/{EPOCHS}]\")\n",
        "\n",
        "        train_loss, train_iou = train_one_epoch(\n",
        "            model, train_loader, optimizer, criterion\n",
        "        )\n",
        "        val_loss, val_iou = validate(model, val_loader, criterion)\n",
        "        scheduler.step()\n",
        "\n",
        "        # ── log ──────────────────────────────────────────────\n",
        "        history[\"train_loss\"].append(train_loss)\n",
        "        history[\"train_iou\"].append(train_iou)\n",
        "        history[\"val_loss\"].append(val_loss)\n",
        "        history[\"val_iou\"].append(val_iou)\n",
        "\n",
        "        print(\n",
        "            f\"  Train → loss: {train_loss:.4f}  mIoU: {train_iou:.4f}\\n\"\n",
        "            f\"  Val   → loss: {val_loss:.4f}  mIoU: {val_iou:.4f}\"\n",
        "        )\n",
        "\n",
        "        # ── save best checkpoint ─────────────────────────────\n",
        "        if val_iou > best_val_iou:\n",
        "            best_val_iou = val_iou\n",
        "            torch.save({\n",
        "                \"epoch\":      epoch,\n",
        "                \"model_state\": model.state_dict(),\n",
        "                \"optimizer_state\": optimizer.state_dict(),\n",
        "                \"val_iou\":    val_iou,\n",
        "                \"val_loss\":   val_loss,\n",
        "            }, best_path)\n",
        "            print(f\"  ✅ Best model saved (val mIoU: {best_val_iou:.4f})\")\n",
        "\n",
        "        print()\n",
        "\n",
        "    # ── final summary ────────────────────────────────────────\n",
        "    print(\"=\" * 50)\n",
        "    print(f\"🏆 Training complete!\")\n",
        "    print(f\"   Best Val mIoU : {best_val_iou:.4f}\")\n",
        "    print(f\"   Checkpoint    : {best_path}\")\n",
        "    print(\"=\" * 50)\n",
        "\n",
        "    plot_curves(history)\n",
        "    return model, history\n",
        "\n",
        "\n",
        "# ── RUN ──────────────────────────────────────────────────────\n",
        "model, history = train()"
      ],
      "metadata": {
        "id": "7Lbx7gKqW2fq"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "print(model)\n"
      ],
      "metadata": {
        "id": "h9yPHyK44AZg"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import torch\n",
        "torch.save(model.state_dict(), \"/content/drive/MyDrive/deeplabv3_desert.pth\")\n",
        "print(\"✅ Saved!\")"
      ],
      "metadata": {
        "id": "j9st7Wc34JPG"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================\n",
        "# DEEPLABV3+ INFERENCE & TESTING\n",
        "# ============================================================\n",
        "\n",
        "import os\n",
        "import numpy as np\n",
        "import torch\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.patches as mpatches\n",
        "from PIL import Image\n",
        "import albumentations as A\n",
        "from albumentations.pytorch import ToTensorV2\n",
        "\n",
        "\n",
        "# ── CONFIG ───────────────────────────────────────────────────\n",
        "MODEL_PATH  = \"/content/drive/MyDrive/deeplabv3_desert.pth\"\n",
        "TEST_DIR    = \"/content/drive/MyDrive/Offroad_Segmentation_Training_Dataset/val/Color_Images\"\n",
        "OUTPUT_DIR  = \"/content/outputs/predictions\"\n",
        "IMAGE_SIZE  = 512\n",
        "DEVICE      = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "print(f\"🖥️  Running on: {DEVICE}\")\n",
        "\n",
        "# ── CLASS INFO ───────────────────────────────────────────────\n",
        "CLASS_NAMES = [\n",
        "    \"Trees\", \"Lush Bushes\", \"Dry Grass\", \"Dry Bushes\",\n",
        "    \"Ground Clutter\", \"Flowers\", \"Logs\", \"Rocks\", \"Landscape\", \"Sky\"\n",
        "]\n",
        "\n",
        "# Distinct colors for each class (RGB)\n",
        "CLASS_COLORS = np.array([\n",
        "    [34,  139, 34 ],   # 0 Trees          → Forest Green\n",
        "    [0,   200, 0  ],   # 1 Lush Bushes    → Bright Green\n",
        "    [210, 180, 140],   # 2 Dry Grass      → Tan\n",
        "    [139, 90,  43 ],   # 3 Dry Bushes     → Brown\n",
        "    [128, 128, 128],   # 4 Ground Clutter → Gray\n",
        "    [255, 105, 180],   # 5 Flowers        → Pink\n",
        "    [101, 67,  33 ],   # 6 Logs           → Dark Brown\n",
        "    [169, 169, 169],   # 7 Rocks          → Light Gray\n",
        "    [210, 180, 100],   # 8 Landscape      → Sand\n",
        "    [135, 206, 235],   # 9 Sky            → Sky Blue\n",
        "], dtype=np.uint8)\n",
        "\n",
        "\n",
        "# ── LOAD MODEL ───────────────────────────────────────────────\n",
        "def load_model(model_path: str):\n",
        "    model = get_model()   # from Cell 2\n",
        "    model.load_state_dict(\n",
        "        torch.load(model_path, map_location=DEVICE)\n",
        "    )\n",
        "    model.eval()\n",
        "    print(f\"✅ Model loaded from: {model_path}\")\n",
        "    return model\n",
        "\n",
        "\n",
        "# ── TRANSFORM ────────────────────────────────────────────────\n",
        "def get_inference_transform():\n",
        "    return A.Compose([\n",
        "        A.Normalize(mean=(0.485, 0.456, 0.406),\n",
        "                    std =(0.229, 0.224, 0.225)),\n",
        "        ToTensorV2(),\n",
        "    ])\n",
        "\n",
        "\n",
        "# ── PREDICT SINGLE IMAGE ─────────────────────────────────────\n",
        "def predict(model, image_path: str):\n",
        "    \"\"\"\n",
        "    Run inference on a single image.\n",
        "    Returns predicted mask as numpy array (H, W) with class indices.\n",
        "    \"\"\"\n",
        "    # Load and resize\n",
        "    image = np.array(\n",
        "        Image.open(image_path).convert(\"RGB\").resize(\n",
        "            (IMAGE_SIZE, IMAGE_SIZE), Image.BILINEAR\n",
        "        ),\n",
        "        dtype=np.uint8\n",
        "    )\n",
        "    original = image.copy()   # keep for visualisation\n",
        "\n",
        "    # Transform\n",
        "    transform = get_inference_transform()\n",
        "    tensor = transform(image=image)[\"image\"]             # (3, H, W)\n",
        "    tensor = tensor.unsqueeze(0).to(DEVICE)              # (1, 3, H, W)\n",
        "\n",
        "    # Inference\n",
        "    with torch.no_grad():\n",
        "        logits = model(tensor)                           # (1, C, H, W)\n",
        "        pred   = logits.argmax(dim=1).squeeze(0)         # (H, W)\n",
        "\n",
        "    return original, pred.cpu().numpy()\n",
        "\n",
        "\n",
        "# ── MASK → COLOR IMAGE ───────────────────────────────────────\n",
        "def colorize_mask(mask: np.ndarray) -> np.ndarray:\n",
        "    \"\"\"Convert class index mask to RGB color image.\"\"\"\n",
        "    color_mask = CLASS_COLORS[mask]   # (H, W, 3)\n",
        "    return color_mask\n",
        "\n",
        "\n",
        "# ── VISUALISE ────────────────────────────────────────────────\n",
        "def visualize_prediction(image, pred_mask, save_path=None, title=\"\"):\n",
        "    color_mask = colorize_mask(pred_mask)\n",
        "\n",
        "    fig, axes = plt.subplots(1, 3, figsize=(18, 6))\n",
        "\n",
        "    # Original image\n",
        "    axes[0].imshow(image)\n",
        "    axes[0].set_title(\"Input Image\", fontsize=12)\n",
        "    axes[0].axis(\"off\")\n",
        "\n",
        "    # Predicted mask (colored)\n",
        "    axes[1].imshow(color_mask)\n",
        "    axes[1].set_title(\"Predicted Mask\", fontsize=12)\n",
        "    axes[1].axis(\"off\")\n",
        "\n",
        "    # Overlay\n",
        "    overlay = (image * 0.6 + color_mask * 0.4).astype(np.uint8)\n",
        "    axes[2].imshow(overlay)\n",
        "    axes[2].set_title(\"Overlay\", fontsize=12)\n",
        "    axes[2].axis(\"off\")\n",
        "\n",
        "    # Legend\n",
        "    legend_patches = [\n",
        "        mpatches.Patch(color=CLASS_COLORS[i]/255, label=CLASS_NAMES[i])\n",
        "        for i in range(len(CLASS_NAMES))\n",
        "    ]\n",
        "    fig.legend(handles=legend_patches, loc=\"lower center\",\n",
        "               ncol=5, fontsize=9, frameon=True,\n",
        "               bbox_to_anchor=(0.5, -0.05))\n",
        "\n",
        "    plt.suptitle(title, fontsize=13)\n",
        "    plt.tight_layout()\n",
        "\n",
        "    if save_path:\n",
        "        plt.savefig(save_path, dpi=150, bbox_inches=\"tight\")\n",
        "        print(f\"💾 Saved → {save_path}\")\n",
        "\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ── CLASS DISTRIBUTION ───────────────────────────────────────\n",
        "def show_class_distribution(pred_mask):\n",
        "    \"\"\"Print how much % of image each class occupies.\"\"\"\n",
        "    total = pred_mask.size\n",
        "    print(\"\\n📊 Class Distribution:\")\n",
        "    print(\"-\" * 35)\n",
        "    for i, name in enumerate(CLASS_NAMES):\n",
        "        count = (pred_mask == i).sum()\n",
        "        pct   = count / total * 100\n",
        "        if pct > 0.1:   # only show classes that are present\n",
        "            bar = \"█\" * int(pct / 2)\n",
        "            print(f\"  {name:<16} {pct:5.1f}%  {bar}\")\n",
        "    print(\"-\" * 35)\n",
        "\n",
        "\n",
        "# ── TEST MULTIPLE IMAGES ─────────────────────────────────────\n",
        "def test_folder(model, test_dir: str, num_images: int = 5):\n",
        "    \"\"\"\n",
        "    Run inference on first N images in a folder.\n",
        "    Saves predictions to OUTPUT_DIR.\n",
        "    \"\"\"\n",
        "    valid_exts = {\".jpg\", \".jpeg\", \".png\", \".bmp\"}\n",
        "    image_files = sorted([\n",
        "        f for f in os.listdir(test_dir)\n",
        "        if os.path.splitext(f)[1].lower() in valid_exts\n",
        "    ])[:num_images]\n",
        "\n",
        "    if not image_files:\n",
        "        print(f\"❌ No images found in {test_dir}\")\n",
        "        return\n",
        "\n",
        "    print(f\"\\n🔍 Testing {len(image_files)} images from:\\n   {test_dir}\\n\")\n",
        "\n",
        "    for fname in image_files:\n",
        "        image_path = os.path.join(test_dir, fname)\n",
        "        save_path  = os.path.join(OUTPUT_DIR, f\"pred_{fname}\")\n",
        "\n",
        "        print(f\"▶ {fname}\")\n",
        "        image, pred_mask = predict(model, image_path)\n",
        "        visualize_prediction(\n",
        "            image, pred_mask,\n",
        "            save_path = save_path,\n",
        "            title     = fname,\n",
        "        )\n",
        "        show_class_distribution(pred_mask)\n",
        "        print()\n",
        "\n",
        "\n",
        "# ── TEST SINGLE IMAGE ────────────────────────────────────────\n",
        "def test_single(model, image_path: str):\n",
        "    \"\"\"Run inference on one specific image.\"\"\"\n",
        "    fname     = os.path.basename(image_path)\n",
        "    save_path = os.path.join(OUTPUT_DIR, f\"pred_{fname}\")\n",
        "\n",
        "    print(f\"▶ Testing: {fname}\")\n",
        "    image, pred_mask = predict(model, image_path)\n",
        "    visualize_prediction(image, pred_mask, save_path=save_path, title=fname)\n",
        "    show_class_distribution(pred_mask)\n",
        "\n",
        "\n",
        "# ── RUN ──────────────────────────────────────────────────────\n",
        "# Load model\n",
        "model = load_model(MODEL_PATH)\n",
        "\n",
        "test_folder(model, TEST_DIR, num_images=20)\n",
        "\n"
      ],
      "metadata": {
        "id": "E4ZlIj8h3sbb"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================\n",
        "# MODEL EVALUATION — ACCURACY METRICS\n",
        "# ============================================================\n",
        "\n",
        "import os\n",
        "import numpy as np\n",
        "import torch\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from sklearn.metrics import confusion_matrix\n",
        "from tqdm import tqdm\n",
        "\n",
        "\n",
        "# ── CONFIG ───────────────────────────────────────────────────\n",
        "MODEL_PATH  = \"/content/drive/MyDrive/deeplabv3_desert.pth\"\n",
        "ROOT_DIR    = \"/content/drive/MyDrive/Offroad_Segmentation_Training_Dataset\"\n",
        "OUTPUT_DIR  = \"/content/outputs\"\n",
        "NUM_CLASSES = 10\n",
        "DEVICE      = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "\n",
        "CLASS_NAMES = [\n",
        "    \"Trees\", \"Lush Bushes\", \"Dry Grass\", \"Dry Bushes\",\n",
        "    \"Ground Clutter\", \"Flowers\", \"Logs\", \"Rocks\", \"Landscape\", \"Sky\"\n",
        "]\n",
        "\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "\n",
        "\n",
        "# ── LOAD MODEL ───────────────────────────────────────────────\n",
        "model = get_model()\n",
        "model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n",
        "model.eval()\n",
        "print(f\"✅ Model loaded | Device: {DEVICE}\\n\")\n",
        "\n",
        "\n",
        "# ── DATALOADER ───────────────────────────────────────────────\n",
        "_, val_loader = get_dataloaders(\n",
        "    root_dir    = ROOT_DIR,\n",
        "    batch_size  = 8,\n",
        "    num_workers = 2,\n",
        "    pin_memory  = (DEVICE.type == \"cuda\"),\n",
        ")\n",
        "\n",
        "\n",
        "# ── METRIC FUNCTIONS ─────────────────────────────────────────\n",
        "\n",
        "def compute_metrics(all_preds, all_targets, num_classes=NUM_CLASSES):\n",
        "    \"\"\"\n",
        "    Compute per-class and overall metrics:\n",
        "    - Pixel Accuracy\n",
        "    - Mean Accuracy\n",
        "    - IoU per class\n",
        "    - Mean IoU (mIoU)\n",
        "    - Dice Score per class\n",
        "    \"\"\"\n",
        "    metrics = {}\n",
        "\n",
        "    # Flatten\n",
        "    preds   = np.concatenate([p.flatten() for p in all_preds])\n",
        "    targets = np.concatenate([t.flatten() for t in all_targets])\n",
        "\n",
        "    # ── Overall Pixel Accuracy ────────────────────────────────\n",
        "    pixel_acc = (preds == targets).mean() * 100\n",
        "    metrics[\"pixel_accuracy\"] = pixel_acc\n",
        "\n",
        "    # ── Per-class metrics ────────────────────────────────────\n",
        "    iou_per_class   = []\n",
        "    dice_per_class  = []\n",
        "    acc_per_class   = []\n",
        "\n",
        "    for cls in range(num_classes):\n",
        "        pred_mask   = (preds   == cls)\n",
        "        target_mask = (targets == cls)\n",
        "\n",
        "        tp = (pred_mask  & target_mask).sum()\n",
        "        fp = (pred_mask  & ~target_mask).sum()\n",
        "        fn = (~pred_mask & target_mask).sum()\n",
        "        tn = (~pred_mask & ~target_mask).sum()\n",
        "\n",
        "        # IoU\n",
        "        union = tp + fp + fn\n",
        "        iou   = (tp / union * 100) if union > 0 else None\n",
        "\n",
        "        # Dice\n",
        "        dice_denom = 2 * tp + fp + fn\n",
        "        dice = (2 * tp / dice_denom * 100) if dice_denom > 0 else None\n",
        "\n",
        "        # Class Accuracy\n",
        "        class_total = target_mask.sum()\n",
        "        acc = (tp / class_total * 100) if class_total > 0 else None\n",
        "\n",
        "        iou_per_class.append(iou)\n",
        "        dice_per_class.append(dice)\n",
        "        acc_per_class.append(acc)\n",
        "\n",
        "    # mIoU — only classes that are present in dataset\n",
        "    valid_ious = [x for x in iou_per_class if x is not None]\n",
        "    metrics[\"miou\"]          = np.mean(valid_ious)\n",
        "    metrics[\"iou_per_class\"] = iou_per_class\n",
        "    metrics[\"dice_per_class\"]= dice_per_class\n",
        "    metrics[\"acc_per_class\"] = acc_per_class\n",
        "\n",
        "    # Mean Accuracy\n",
        "    valid_accs = [x for x in acc_per_class if x is not None]\n",
        "    metrics[\"mean_accuracy\"] = np.mean(valid_accs)\n",
        "\n",
        "    return metrics\n",
        "\n",
        "\n",
        "# ── RUN EVALUATION ───────────────────────────────────────────\n",
        "def evaluate(model, loader):\n",
        "    all_preds   = []\n",
        "    all_targets = []\n",
        "\n",
        "    print(\"🔍 Running evaluation on val set...\")\n",
        "    with torch.no_grad():\n",
        "        for images, masks in tqdm(loader, desc=\"  Evaluating\"):\n",
        "            images = images.to(DEVICE)\n",
        "            logits = model(images)\n",
        "            preds  = logits.argmax(dim=1)\n",
        "\n",
        "            all_preds.append(preds.cpu().numpy())\n",
        "            all_targets.append(masks.numpy())\n",
        "\n",
        "    return compute_metrics(all_preds, all_targets)\n",
        "\n",
        "\n",
        "# ── PRINT RESULTS ────────────────────────────────────────────\n",
        "def print_results(metrics):\n",
        "    print(\"\\n\" + \"=\" * 55)\n",
        "    print(\"  📊 EVALUATION RESULTS\")\n",
        "    print(\"=\" * 55)\n",
        "    print(f\"  Pixel Accuracy : {metrics['pixel_accuracy']:.2f}%\")\n",
        "    print(f\"  Mean Accuracy  : {metrics['mean_accuracy']:.2f}%\")\n",
        "    print(f\"  Mean IoU       : {metrics['miou']:.2f}%\")\n",
        "    print(\"=\" * 55)\n",
        "\n",
        "    print(f\"\\n  {'Class':<18} {'IoU':>8} {'Dice':>8} {'Acc':>8}\")\n",
        "    print(\"  \" + \"-\" * 46)\n",
        "\n",
        "    for i, name in enumerate(CLASS_NAMES):\n",
        "        iou  = metrics[\"iou_per_class\"][i]\n",
        "        dice = metrics[\"dice_per_class\"][i]\n",
        "        acc  = metrics[\"acc_per_class\"][i]\n",
        "\n",
        "        iou_str  = f\"{iou:.1f}%\"  if iou  is not None else \"  N/A\"\n",
        "        dice_str = f\"{dice:.1f}%\" if dice is not None else \"  N/A\"\n",
        "        acc_str  = f\"{acc:.1f}%\"  if acc  is not None else \"  N/A\"\n",
        "\n",
        "        print(f\"  {name:<18} {iou_str:>8} {dice_str:>8} {acc_str:>8}\")\n",
        "\n",
        "    print(\"=\" * 55)\n",
        "\n",
        "\n",
        "# ── CONFUSION MATRIX ─────────────────────────────────────────\n",
        "def plot_confusion_matrix(all_preds, all_targets):\n",
        "    preds   = np.concatenate([p.flatten() for p in all_preds])\n",
        "    targets = np.concatenate([t.flatten() for t in all_targets])\n",
        "\n",
        "    cm = confusion_matrix(targets, preds, labels=list(range(NUM_CLASSES)))\n",
        "\n",
        "    # Normalize per row (true class)\n",
        "    cm_norm = cm.astype(float)\n",
        "    row_sum = cm.sum(axis=1, keepdims=True)\n",
        "    cm_norm = np.divide(cm_norm, row_sum,\n",
        "                        where=row_sum != 0) * 100\n",
        "\n",
        "    fig, ax = plt.subplots(figsize=(12, 10))\n",
        "    sns.heatmap(\n",
        "        cm_norm,\n",
        "        annot     = True,\n",
        "        fmt       = \".1f\",\n",
        "        cmap      = \"Blues\",\n",
        "        xticklabels = CLASS_NAMES,\n",
        "        yticklabels = CLASS_NAMES,\n",
        "        ax        = ax,\n",
        "    )\n",
        "    ax.set_xlabel(\"Predicted Class\", fontsize=11)\n",
        "    ax.set_ylabel(\"True Class\",      fontsize=11)\n",
        "    ax.set_title(\"Confusion Matrix (% per true class)\", fontsize=13)\n",
        "    plt.xticks(rotation=45, ha=\"right\")\n",
        "    plt.yticks(rotation=0)\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(os.path.join(OUTPUT_DIR, \"confusion_matrix.png\"),\n",
        "                dpi=150, bbox_inches=\"tight\")\n",
        "    plt.show()\n",
        "    print(\"💾 Saved → /content/outputs/confusion_matrix.png\")\n",
        "\n",
        "\n",
        "# ── IoU BAR CHART ────────────────────────────────────────────\n",
        "def plot_iou_bar(metrics):\n",
        "    ious   = [x if x is not None else 0 for x in metrics[\"iou_per_class\"]]\n",
        "    colors = [\"#2ecc71\" if v >= 50 else \"#e74c3c\" for v in ious]\n",
        "\n",
        "    fig, ax = plt.subplots(figsize=(12, 5))\n",
        "    bars = ax.bar(CLASS_NAMES, ious, color=colors, edgecolor=\"white\", linewidth=0.8)\n",
        "\n",
        "    # Value labels on bars\n",
        "    for bar, val in zip(bars, ious):\n",
        "        ax.text(bar.get_x() + bar.get_width() / 2,\n",
        "                bar.get_height() + 0.5,\n",
        "                f\"{val:.1f}%\", ha=\"center\", va=\"bottom\", fontsize=9)\n",
        "\n",
        "    ax.axhline(y=metrics[\"miou\"], color=\"blue\",\n",
        "               linestyle=\"--\", linewidth=1.5,\n",
        "               label=f\"mIoU = {metrics['miou']:.1f}%\")\n",
        "\n",
        "    ax.set_ylim(0, 110)\n",
        "    ax.set_ylabel(\"IoU (%)\")\n",
        "    ax.set_title(\"Per-Class IoU Score\")\n",
        "    ax.legend()\n",
        "    plt.xticks(rotation=30, ha=\"right\")\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(os.path.join(OUTPUT_DIR, \"iou_per_class.png\"),\n",
        "                dpi=150, bbox_inches=\"tight\")\n",
        "    plt.show()\n",
        "    print(\"💾 Saved → /content/outputs/iou_per_class.png\")\n",
        "\n",
        "\n",
        "# ── RUN ALL ──────────────────────────────────────────────────\n",
        "# 1. Collect all predictions\n",
        "all_preds, all_targets = [], []\n",
        "\n",
        "with torch.no_grad():\n",
        "    for images, masks in tqdm(val_loader, desc=\"🔍 Evaluating\"):\n",
        "        images = images.to(DEVICE)\n",
        "        preds  = model(images).argmax(dim=1)\n",
        "        all_preds.append(preds.cpu().numpy())\n",
        "        all_targets.append(masks.numpy())\n",
        "\n",
        "# 2. Compute metrics\n",
        "metrics = compute_metrics(all_preds, all_targets)\n",
        "\n",
        "# 3. Print results\n",
        "print_results(metrics)\n",
        "\n",
        "# 4. Plot graphs\n",
        "plot_iou_bar(metrics)\n",
        "plot_confusion_matrix(all_preds, all_targets)"
      ],
      "metadata": {
        "id": "NxfaqZU1307P"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import shutil\n",
        "\n",
        "shutil.copy(\n",
        "    \"/content/outputs/best_model.pth\",\n",
        "    \"/content/drive/MyDrive/deeplabv3_desert_best.pth\"\n",
        ")\n",
        "print(\"✅ Model saved to Google Drive!\")"
      ],
      "metadata": {
        "id": "-W2AiNvGJbL8"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# HuggingFace hub install karo\n",
        "!pip install -q huggingface_hub\n",
        "\n",
        "from huggingface_hub import HfApi\n",
        "api = HfApi()\n",
        "\n",
        "# Apna token aur username yahan daalo\n",
        "HF_TOKEN    = \"\"   # Step 2 ka token\n",
        "HF_USERNAME = \"\"          # HF username\n",
        "REPO_NAME   = \"desert-segmentation\"\n",
        "\n",
        "# Model upload karo\n",
        "api.upload_file(\n",
        "    path_or_fileobj = \"/content/drive/MyDrive/deeplabv3_desert_best.pth\",\n",
        "    path_in_repo    = \"deeplabv3_desert_best.pth\",\n",
        "    repo_id         = f\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    repo_type       = \"space\",\n",
        "    token           = HF_TOKEN,\n",
        ")\n",
        "print(\"✅ Model uploaded to HuggingFace!\")"
      ],
      "metadata": {
        "id": "sm4nEQUvDH7a"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "print(os.path.exists(\"/content/drive/MyDrive/deeplabv3_desert_best.pth\"))"
      ],
      "metadata": {
        "id": "VaLV-WxjZN96"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "HF_USERNAME = \"Aadarshhhhhhhh\""
      ],
      "metadata": {
        "id": "93mXzZBCcuTA"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "app_code = '''\n",
        "import gradio as gr\n",
        "import torch\n",
        "import numpy as np\n",
        "from PIL import Image\n",
        "import albumentations as A\n",
        "from albumentations.pytorch import ToTensorV2\n",
        "import segmentation_models_pytorch as smp\n",
        "from huggingface_hub import hf_hub_download\n",
        "\n",
        "# ── CONFIG ───────────────────────────────────────────────────\n",
        "DEVICE      = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "NUM_CLASSES = 10\n",
        "IMAGE_SIZE  = 512\n",
        "\n",
        "CLASS_NAMES = [\n",
        "    \"Trees\", \"Lush Bushes\", \"Dry Grass\", \"Dry Bushes\",\n",
        "    \"Ground Clutter\", \"Flowers\", \"Logs\", \"Rocks\", \"Landscape\", \"Sky\"\n",
        "]\n",
        "\n",
        "CLASS_COLORS = np.array([\n",
        "    [34,  139, 34 ],\n",
        "    [0,   200, 0  ],\n",
        "    [210, 180, 140],\n",
        "    [139, 90,  43 ],\n",
        "    [128, 128, 128],\n",
        "    [255, 105, 180],\n",
        "    [101, 67,  33 ],\n",
        "    [169, 169, 169],\n",
        "    [210, 180, 100],\n",
        "    [135, 206, 235],\n",
        "], dtype=np.uint8)\n",
        "\n",
        "# ── LOAD MODEL ───────────────────────────────────────────────\n",
        "def get_model():\n",
        "    model = smp.DeepLabV3Plus(\n",
        "        encoder_name    = \"resnet50\",\n",
        "        encoder_weights = None,\n",
        "        in_channels     = 3,\n",
        "        classes         = NUM_CLASSES,\n",
        "        activation      = None,\n",
        "    )\n",
        "    return model\n",
        "\n",
        "model_path = hf_hub_download(\n",
        "    repo_id   = \"YOUR_USERNAME/desert-segmentation\",\n",
        "    filename  = \"deeplabv3_desert_best.pth\",\n",
        "    repo_type = \"space\",\n",
        ")\n",
        "model = get_model()\n",
        "model.load_state_dict(torch.load(model_path, map_location=DEVICE))\n",
        "model.eval().to(DEVICE)\n",
        "\n",
        "# ── PREDICT ───────────────────────────────────────────────────\n",
        "def predict(input_image):\n",
        "    image = np.array(\n",
        "        Image.fromarray(input_image).resize(\n",
        "            (IMAGE_SIZE, IMAGE_SIZE), Image.BILINEAR\n",
        "        ),\n",
        "        dtype=np.uint8\n",
        "    )\n",
        "    transform = A.Compose([\n",
        "        A.Normalize(mean=(0.485, 0.456, 0.406),\n",
        "                    std =(0.229, 0.224, 0.225)),\n",
        "        ToTensorV2(),\n",
        "    ])\n",
        "    tensor = transform(image=image)[\"image\"].unsqueeze(0).to(DEVICE)\n",
        "\n",
        "    with torch.no_grad():\n",
        "        pred = model(tensor).argmax(dim=1).squeeze(0).cpu().numpy()\n",
        "\n",
        "    color_mask = CLASS_COLORS[pred]\n",
        "    overlay    = (image * 0.6 + color_mask * 0.4).astype(np.uint8)\n",
        "\n",
        "    return Image.fromarray(color_mask), Image.fromarray(overlay)\n",
        "\n",
        "# ── GRADIO UI ─────────────────────────────────────────────────\n",
        "demo = gr.Interface(\n",
        "    fn      = predict,\n",
        "    inputs  = gr.Image(type=\"numpy\", label=\"Upload Desert Image\"),\n",
        "    outputs = [\n",
        "        gr.Image(type=\"pil\", label=\"Segmentation Mask\"),\n",
        "        gr.Image(type=\"pil\", label=\"Overlay\"),\n",
        "    ],\n",
        "    title       = \"🌵 Desert Environment Segmentation\",\n",
        "    description = \"DeepLabV3+ model trained on desert environment dataset. Upload an image to get segmentation.\",\n",
        ")\n",
        "\n",
        "demo.launch()\n",
        "'''\n",
        "\n",
        "# app.py file save karo\n",
        "with open(\"/content/app.py\", \"w\") as f:\n",
        "    f.write(app_code)\n",
        "\n",
        "print(\"✅ app.py created!\")"
      ],
      "metadata": {
        "id": "nD6EL9MjZY6Z"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "requirements = \"\"\"torch\n",
        "torchvision\n",
        "segmentation_models_pytorch\n",
        "albumentations\n",
        "gradio\n",
        "huggingface_hub\n",
        "Pillow>=9.0,<11.0\n",
        "numpy\n",
        "\"\"\"\n",
        "\n",
        "with open(\"/content/requirements.txt\", \"w\") as f:\n",
        "    f.write(requirements)\n",
        "\n",
        "print(\"✅ requirements.txt created!\")"
      ],
      "metadata": {
        "id": "AdwHrMTZc9RT"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Apna actual HF username yahan daalo\n",
        "HF_USERNAME = \"Aadarshhhhhhhh\"          # ← YAHAN APNA USERNAME DAALO\n",
        "REPO_NAME   = \"desert-segmentation\"\n",
        "HF_TOKEN    = \"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\"  # ← apna token\n",
        "\n",
        "# app.py ko sahi username ke saath dobara likho\n",
        "app_code = f'''\n",
        "import gradio as gr\n",
        "import torch\n",
        "import numpy as np\n",
        "from PIL import Image\n",
        "import albumentations as A\n",
        "from albumentations.pytorch import ToTensorV2\n",
        "import segmentation_models_pytorch as smp\n",
        "from huggingface_hub import hf_hub_download\n",
        "\n",
        "DEVICE      = torch.device(\"cpu\")\n",
        "NUM_CLASSES = 10\n",
        "IMAGE_SIZE  = 512\n",
        "\n",
        "CLASS_NAMES = [\n",
        "    \"Trees\", \"Lush Bushes\", \"Dry Grass\", \"Dry Bushes\",\n",
        "    \"Ground Clutter\", \"Flowers\", \"Logs\", \"Rocks\", \"Landscape\", \"Sky\"\n",
        "]\n",
        "\n",
        "CLASS_COLORS = np.array([\n",
        "    [34,  139, 34 ], [0,   200, 0  ], [210, 180, 140],\n",
        "    [139, 90,  43 ], [128, 128, 128], [255, 105, 180],\n",
        "    [101, 67,  33 ], [169, 169, 169], [210, 180, 100],\n",
        "    [135, 206, 235],\n",
        "], dtype=np.uint8)\n",
        "\n",
        "def get_model():\n",
        "    return smp.DeepLabV3Plus(\n",
        "        encoder_name=\"resnet50\", encoder_weights=None,\n",
        "        in_channels=3, classes=10, activation=None,\n",
        "    )\n",
        "\n",
        "model_path = hf_hub_download(\n",
        "    repo_id=\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    filename=\"deeplabv3_desert_best.pth\",\n",
        "    repo_type=\"space\",\n",
        ")\n",
        "model = get_model()\n",
        "model.load_state_dict(torch.load(model_path, map_location=\"cpu\"))\n",
        "model.eval()\n",
        "\n",
        "transform = A.Compose([\n",
        "    A.Normalize(mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225)),\n",
        "    A.pytorch.ToTensorV2(),\n",
        "])\n",
        "\n",
        "def predict(input_image):\n",
        "    image = np.array(\n",
        "        Image.fromarray(input_image).resize((512,512), Image.BILINEAR),\n",
        "        dtype=np.uint8\n",
        "    )\n",
        "    tensor = transform(image=image)[\"image\"].unsqueeze(0)\n",
        "    with torch.no_grad():\n",
        "        pred = model(tensor).argmax(dim=1).squeeze(0).numpy()\n",
        "    color_mask = CLASS_COLORS[pred]\n",
        "    overlay    = (image * 0.6 + color_mask * 0.4).astype(np.uint8)\n",
        "    total = pred.size\n",
        "    info  = \"**Class Distribution:**\\\\n\"\n",
        "    for i, name in enumerate(CLASS_NAMES):\n",
        "        pct = (pred == i).sum() / total * 100\n",
        "        if pct > 0.5:\n",
        "            info += f\"`{{name:<16}}` {{pct:5.1f}}%  {{'█' * int(pct/3)}}\\\\n\"\n",
        "    return Image.fromarray(color_mask), Image.fromarray(overlay), info\n",
        "\n",
        "demo = gr.Interface(\n",
        "    fn=predict,\n",
        "    inputs=gr.Image(type=\"numpy\", label=\"Upload Image\"),\n",
        "    outputs=[\n",
        "        gr.Image(type=\"pil\", label=\"Segmentation Mask\"),\n",
        "        gr.Image(type=\"pil\", label=\"Overlay\"),\n",
        "        gr.Markdown(),\n",
        "    ],\n",
        "    title=\"Desert Segmentation\",\n",
        ")\n",
        "demo.launch()\n",
        "'''\n",
        "\n",
        "# File save karo\n",
        "with open(\"/content/app.py\", \"w\") as f:\n",
        "    f.write(app_code)\n",
        "print(\"✅ app.py ready!\")\n",
        "\n",
        "# HF pe dobara upload karo\n",
        "from huggingface_hub import HfApi\n",
        "api = HfApi()\n",
        "\n",
        "api.upload_file(\n",
        "    path_or_fileobj = \"/content/app.py\",\n",
        "    path_in_repo    = \"app.py\",\n",
        "    repo_id         = f\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    repo_type       = \"space\",\n",
        "    token           = HF_TOKEN,\n",
        ")\n",
        "print(\"✅ app.py uploaded to HF!\")"
      ],
      "metadata": {
        "id": "IyJW5wxed5dV"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "HF_USERNAME = \"Aadarshhhhhhhh\"       # ← apna username\n",
        "REPO_NAME   = \"desert-segmentation\"\n",
        "HF_TOKEN    = \"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\"     # ← apna token\n",
        "\n",
        "# Sirf yeh ek line fix hai:\n",
        "# torch.load(model_path, map_location=\"cpu\")\n",
        "# →\n",
        "# torch.load(model_path, map_location=\"cpu\", weights_only=False)\n",
        "\n",
        "import re\n",
        "\n",
        "with open(\"/content/app.py\", \"r\") as f:\n",
        "    content = f.read()\n",
        "\n",
        "content = content.replace(\n",
        "    'torch.load(model_path, map_location=\"cpu\")',\n",
        "    'torch.load(model_path, map_location=\"cpu\", weights_only=False)'\n",
        ")\n",
        "\n",
        "with open(\"/content/app.py\", \"w\") as f:\n",
        "    f.write(content)\n",
        "\n",
        "print(\"✅ Fixed!\")\n",
        "\n",
        "# Dobara upload karo\n",
        "from huggingface_hub import HfApi\n",
        "api = HfApi()\n",
        "api.upload_file(\n",
        "    path_or_fileobj = \"/content/app.py\",\n",
        "    path_in_repo    = \"app.py\",\n",
        "    repo_id         = f\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    repo_type       = \"space\",\n",
        "    token           = HF_TOKEN,\n",
        ")\n",
        "print(\"✅ app.py re-uploaded!\")"
      ],
      "metadata": {
        "id": "XSoK5I4tgZIy"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from huggingface_hub import HfApi\n",
        "api = HfApi()\n",
        "\n",
        "HF_TOKEN    = \"\"\n",
        "HF_USERNAME = \"\"\n",
        "REPO_NAME   = \"desert-segmentation\"\n",
        "\n",
        "# app.py upload\n",
        "api.upload_file(\n",
        "    path_or_fileobj = \"/content/app.py\",\n",
        "    path_in_repo    = \"app.py\",\n",
        "    repo_id         = f\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    repo_type       = \"space\",\n",
        "    token           = HF_TOKEN,\n",
        ")\n",
        "\n",
        "# requirements.txt upload\n",
        "api.upload_file(\n",
        "    path_or_fileobj = \"/content/requirements.txt\",\n",
        "    path_in_repo    = \"requirements.txt\",\n",
        "    repo_id         = f\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    repo_type       = \"space\",\n",
        "    token           = HF_TOKEN,\n",
        ")\n",
        "\n",
        "print(\"✅ All files uploaded!\")\n",
        "print(f\"🌐 Space URL: https://huggingface.co/spaces/{HF_USERNAME}/{REPO_NAME}\")"
      ],
      "metadata": {
        "id": "E7HNjL8Wdd2_"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "HF_USERNAME = \"\"\n",
        "REPO_NAME   = \"desert-segmentation\"\n",
        "HF_TOKEN    = \"\"\n",
        "\n",
        "with open(\"/content/app.py\", \"r\") as f:\n",
        "    content = f.read()\n",
        "\n",
        "# Purani line replace karo\n",
        "content = content.replace(\n",
        "    'model.load_state_dict(torch.load(model_path, map_location=\"cpu\", weights_only=False))',\n",
        "    '''checkpoint = torch.load(model_path, map_location=\"cpu\", weights_only=False)\n",
        "# Full checkpoint tha — model_state key se load karo\n",
        "if isinstance(checkpoint, dict) and \"model_state\" in checkpoint:\n",
        "    model.load_state_dict(checkpoint[\"model_state\"])\n",
        "else:\n",
        "    model.load_state_dict(checkpoint)'''\n",
        ")\n",
        "\n",
        "with open(\"/content/app.py\", \"w\") as f:\n",
        "    f.write(content)\n",
        "\n",
        "print(\"✅ Fixed!\")\n",
        "\n",
        "# Dobara upload\n",
        "from huggingface_hub import HfApi\n",
        "api = HfApi()\n",
        "api.upload_file(\n",
        "    path_or_fileobj = \"/content/app.py\",\n",
        "    path_in_repo    = \"app.py\",\n",
        "    repo_id         = f\"{HF_USERNAME}/{REPO_NAME}\",\n",
        "    repo_type       = \"space\",\n",
        "    token           = HF_TOKEN,\n",
        ")\n",
        "print(\"✅ Re-uploaded!\")"
      ],
      "metadata": {
        "id": "TpzE79bBiEuq"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "6DFAefWviPKD"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}